### PR TITLE
Buffered requests

### PR DESCRIPTION
**Pull request by joshfisher**
tries to flush a buffer of `NSURLRequest` on background & terminate. i could add writing the buffered requests to disk in the case where the background task runs out of time or is is killed. raven doesn't play nice with `Crashlytics`, which is a bummer & will prevent reporting crashing issues to sentry. i could work around it, depends on how thorough we want to be

### CODE REVIEW

**Comment by csmulhern** [comment]
I was hoping we could send a single request with all the events at once. Is there an endpoint that supports a bulk of events?

**Comment by joshfisher** [comment]
no... there was some chatter in their github issues about supporting it but it doesn't seem like they've made progress on it. at least, the docs don't suggest it as a possibility

**Comment by csmulhern** [comment]
Oh what a shame, maybe there's no point buffering for now then if we're still going to create so many requests.

**Comment by joshfisher** [comment]
but at least they'll get put off until backgrounding rather than mucking up the user experience

**Comment by csmulhern** [comment]
Fair enough. LGTM.

**Pull request merged**
